### PR TITLE
icebram: Complete rewrite to cleanup and make it work

### LINKED ISSUE #301: icebram incompatible with new memory_libmap
### Version

Yosys 0.21+1 (git sha1 b7bf68501, gcc 11.2.0-19ubuntu1 -fPIC -Os)

### Reproduction Steps

I'm getting some strange behavior with yosys >0.17+16, and I think d7dc2313b915 ("ice40: Use `memory_libmap` pass.") might be the issue.

To reproduce, clone icestorm (https://github.com/YosysHQ/icestorm.git), and build `icebram`.
```
cd icebram
make
while true; do bash ./rundemo.sh |& grep 'Found and replaced '; done
```

### Expected Behavior

`Found and replaced` string should never be zero. All yosys <= 0.17+16 outputs e.g.:

```
Found and replaced 1 instances of the memory.
Found and replaced 1 instances of the memory.
Found and replaced 2 instances of the memory.
Found and replaced 3 instances of the memory.
Found and replaced 3 instances of the memory.
Found and replaced 2 instances of the memory.
Found and replaced 2 instances of the memory.
Found and replaced 1 instances of the memory.
Found and replaced 1 instances of the memory.
Found and replaced 1 instances of the memory.
Found and replaced 3 instances of the memory.
```

### Actual Behavior

icebram should be able to find a "ram_data" section to replace, but almost always, it fails to do so:
```
$ while true; do bash ./rundemo.sh |& grep 'Found and replaced '; done
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 1 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 4 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 3 instances of the memory.
Found and replaced 0 instances of the memory.
Found and replaced 0 instances of the memory.
^C
```

### PR DESCRIPTION
**Pull request by smunaut**
Fixes #301 

I know it's a large diff, but it's pretty much a rewrite since the old structure of one giant main() function was becoming unwieldy.

icebram used to parse each .ram_data line one at a time but now it needs to load the whole memory. It also needs to know the READ_MODE (and so parse the ram config tile).

### CODE REVIEW

File: icebram/icebram.cc [hunk 1]
```diff
@@ -76,335 +147,562 @@ void parse_hexfile_line(const char *filename, int linenr, vector<vector<bool>> &
...
+	m_pos{pos[0], pos[1]},
+	m_data_line(-1), m_config_line(-1), m_lines(lines)
+{
+
+}
+
+void
+EBRData::load_data()
+{
+	auto si = this->m_lines.begin() + this->m_data_line + 16;
```
Comment (gatecat) [inline icebram/icebram.cc:272]: is there any reason you're using `->begin() + i` rather than `->at(i)`?

Comment (gatecat) [reply icebram/icebram.cc:272]: oh, I see, you need it as an iterator later on, never mind
